name: Release Drafter

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Update Release Draft
        uses: release-drafter/release-drafter@v5
        with:
          name: Release ${{ github.ref_name }}
          tag: v${{ github.ref_name }}
          publish: false
          prerelease: false
          config-name: release-drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 